*&---------------------------------------------------------------------*
*& Include LZ_CTD_RULES_MATREGF02
*&---------------------------------------------------------------------*
*& Purpose: Validation and Update Subroutines
*& Author: Generated by Cursor AI
*& Date: 2026-01-08
*& SAP Version: NetWeaver 7.31
*&---------------------------------------------------------------------*

" BEGIN: Cursor Generated Code

*&---------------------------------------------------------------------*
*&      Form  VALIDATE_MATERIAL_REGION
*&---------------------------------------------------------------------*
*       Validate material and region consistency per trip
*       Business Rules:
*       1. All loaded legs must have same MATERIAL
*       2. All loaded legs must have same SOURCE_REGION
*       3. All loaded legs must have same DEST_REGION
*       4. Material-Region combination must exist in configuration
*----------------------------------------------------------------------*
*      -->PT_LOADED_LEGS  Loaded legs table
*      -->PT_CONFIG       Configuration table
*      <--PT_VALIDATION   Validation results
*      <--PV_ERROR_FLAG   Error flag
*      <--PV_MESSAGE      Error message
*----------------------------------------------------------------------*
FORM validate_material_region
  TABLES pt_loaded_legs TYPE tt_trip_itm_enr
         pt_config      TYPE tt_config
  CHANGING pt_validation TYPE tt_validation
           pv_error_flag TYPE abap_bool
           pv_message    TYPE string.

  DATA: lt_unique_trips TYPE TABLE OF ztrip_no,
        lv_trip_no      TYPE ztrip_no,
        lw_validation   TYPE ty_validation,
        lw_loaded_leg   TYPE ty_trip_itm_enr,
        lw_config       TYPE ty_config,
        lt_temp_mat     TYPE TABLE OF matnr,
        lt_temp_src     TYPE TABLE OF regio,
        lt_temp_dst     TYPE TABLE OF regio,
        lv_matnr        TYPE matnr,
        lv_src_region   TYPE regio,
        lv_dst_region   TYPE regio,
        lv_cnt_mat      TYPE i,
        lv_cnt_src      TYPE i,
        lv_cnt_dst      TYPE i,
        lv_cnt_legs     TYPE i,
        lv_config_found TYPE abap_bool.

  CLEAR: pv_error_flag, pv_message.
  REFRESH pt_validation.

  " ==============================================================
  " Step 1: Get unique trip numbers from loaded legs
  " ==============================================================
  REFRESH lt_unique_trips.
  LOOP AT pt_loaded_legs INTO lw_loaded_leg.
    APPEND lw_loaded_leg-trip_no TO lt_unique_trips.
  ENDLOOP.
  SORT lt_unique_trips.
  DELETE ADJACENT DUPLICATES FROM lt_unique_trips.

  " ==============================================================
  " Step 2: Validate each trip independently
  " ==============================================================
  LOOP AT lt_unique_trips INTO lv_trip_no.
    CLEAR: lw_validation,
           lt_temp_mat,
           lt_temp_src,
           lt_temp_dst,
           lv_cnt_legs.

    lw_validation-trip_no = lv_trip_no.
    lw_validation-is_valid = abap_true.

    " Collect materials and regions for this trip
    LOOP AT pt_loaded_legs INTO lw_loaded_leg
      WHERE trip_no = lv_trip_no.

      lv_cnt_legs = lv_cnt_legs + 1.
      APPEND lw_loaded_leg-material TO lt_temp_mat.
      APPEND lw_loaded_leg-source_region TO lt_temp_src.
      APPEND lw_loaded_leg-dest_region TO lt_temp_dst.
    ENDLOOP.

    lw_validation-loaded_legs = lv_cnt_legs.

    " ==============================================================
    " Validation Check 1: Unique Materials
    " All loaded legs must have the SAME material
    " ==============================================================
    SORT lt_temp_mat.
    DELETE ADJACENT DUPLICATES FROM lt_temp_mat.
    DESCRIBE TABLE lt_temp_mat LINES lv_cnt_mat.

    IF lv_cnt_mat > 1.
      lw_validation-is_valid = abap_false.
      lw_validation-message = gc_msg_mult_mat.
      APPEND lw_validation TO pt_validation.
      CONTINUE.
    ENDIF.

    READ TABLE lt_temp_mat INTO lv_matnr INDEX 1.
    IF sy-subrc = 0.
      lw_validation-matnr = lv_matnr.
    ENDIF.

    " ==============================================================
    " Validation Check 2: Unique Source Regions
    " All loaded legs must have the SAME source region
    " ==============================================================
    SORT lt_temp_src.
    DELETE ADJACENT DUPLICATES FROM lt_temp_src.
    DESCRIBE TABLE lt_temp_src LINES lv_cnt_src.

    IF lv_cnt_src > 1.
      lw_validation-is_valid = abap_false.
      lw_validation-message = gc_msg_mult_src_reg.
      APPEND lw_validation TO pt_validation.
      CONTINUE.
    ENDIF.

    READ TABLE lt_temp_src INTO lv_src_region INDEX 1.
    IF sy-subrc = 0.
      lw_validation-source_region = lv_src_region.
    ENDIF.

    " ==============================================================
    " Validation Check 3: Unique Destination Regions
    " All loaded legs must have the SAME destination region
    " ==============================================================
    SORT lt_temp_dst.
    DELETE ADJACENT DUPLICATES FROM lt_temp_dst.
    DESCRIBE TABLE lt_temp_dst LINES lv_cnt_dst.

    IF lv_cnt_dst > 1.
      lw_validation-is_valid = abap_false.
      lw_validation-message = gc_msg_mult_dst_reg.
      APPEND lw_validation TO pt_validation.
      CONTINUE.
    ENDIF.

    READ TABLE lt_temp_dst INTO lv_dst_region INDEX 1.
    IF sy-subrc = 0.
      lw_validation-dest_region = lv_dst_region.
    ENDIF.

    " ==============================================================
    " Validation Check 4: Configuration Match
    " Material-Region combination must exist in configuration table
    " Check both source and destination regions
    " ==============================================================
    lv_config_found = abap_false.

    " Check configuration for source region
    READ TABLE pt_config INTO lw_config
      WITH KEY matnr = lv_matnr
               region = lv_src_region
      BINARY SEARCH.

    IF sy-subrc = 0.
      lv_config_found = abap_true.
    ENDIF.

    " Check configuration for destination region
    IF lv_config_found = abap_false.
      READ TABLE pt_config INTO lw_config
        WITH KEY matnr = lv_matnr
                 region = lv_dst_region
        BINARY SEARCH.

      IF sy-subrc = 0.
        lv_config_found = abap_true.
      ENDIF.
    ENDIF.

    IF lv_config_found = abap_false.
      lw_validation-is_valid = abap_false.
      lw_validation-message = gc_msg_no_config.
    ELSE.
      lw_validation-message = gc_msg_success.
    ENDIF.

    APPEND lw_validation TO pt_validation.
  ENDLOOP.

  " ==============================================================
  " Final Check: At least one trip must pass validation
  " ==============================================================
  READ TABLE pt_validation INTO lw_validation
    WITH KEY is_valid = abap_true.

  IF sy-subrc <> 0.
    pv_error_flag = abap_true.
    " Return first validation failure message
    READ TABLE pt_validation INTO lw_validation INDEX 1.
    IF sy-subrc = 0.
      pv_message = lw_validation-message.
    ELSE.
      pv_message = 'Validation failed for all trips'.
    ENDIF.
  ENDIF.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  UPDATE_CTD_ELIGIBILITY
*&---------------------------------------------------------------------*
*       Update CTD eligibility flags for validated trips
*       Business Rule: Update ALL legs in trip (including empty legs)
*----------------------------------------------------------------------*
*      -->PT_VALIDATION      Validation results
*      <->PT_TRIP_HDR        Trip Header table (updated)
*      <->PT_TRIP_ITM        Trip Items table (updated)
*      <--PV_TRIPS_PROC      Trips processed count
*      <--PV_TRIPS_ELIGIBLE  Trips eligible count
*----------------------------------------------------------------------*
FORM update_ctd_eligibility
  TABLES pt_validation TYPE tt_validation
  CHANGING pt_trip_hdr       TYPE STANDARD TABLE
           pt_trip_itm       TYPE STANDARD TABLE
           pv_trips_proc     TYPE i
           pv_trips_eligible TYPE i.

  DATA: lw_validation TYPE ty_validation,
        lv_trip_no    TYPE ztrip_no.

  FIELD-SYMBOLS: <lfs_trip_hdr> TYPE zsce_ctd_hdr,
                 <lfs_trip_itm> TYPE zsce_ctd_itm.

  CLEAR: pv_trips_proc, pv_trips_eligible.

  LOOP AT pt_validation INTO lw_validation.
    pv_trips_proc = pv_trips_proc + 1.

    " Only update if validation passed
    IF lw_validation-is_valid = abap_true.
      pv_trips_eligible = pv_trips_eligible + 1.
      lv_trip_no = lw_validation-trip_no.

      " ==============================================================
      " Update Trip Header
      " - TRIP_STATUS = '08' (CTD Rule Engine Executed)
      " - CTD_RULEENG_REMARKS = 'Material Region Rule Applied'
      " ==============================================================
      LOOP AT pt_trip_hdr ASSIGNING <lfs_trip_hdr>
        WHERE trip_no = lv_trip_no.

        <lfs_trip_hdr>-trip_status = gc_trip_stat_exec.
        <lfs_trip_hdr>-ctd_ruleeng_remarks = gc_remark_applied.
        <lfs_trip_hdr>-modified_by = sy-uname.
        <lfs_trip_hdr>-modified_date = sy-datum.
      ENDLOOP.

      " ==============================================================
      " Update Trip Items (ALL items including empty legs)
      " - CTD_ELIGIBLE = 'X'
      " ==============================================================
      LOOP AT pt_trip_itm ASSIGNING <lfs_trip_itm>
        WHERE trip_no = lv_trip_no.

        <lfs_trip_itm>-ctd_eligible = gc_ctd_eligible.
      ENDLOOP.
    ENDIF.
  ENDLOOP.

ENDFORM.

" END: Cursor Generated Code
