*&---------------------------------------------------------------------*
*& Include LZ_CTD_RULESTOP (or LZSCE_CTD_RULESTOP if using same group)
*&---------------------------------------------------------------------*
*& Purpose: Type definitions for Material & Region Validation Rule
*& Author: Generated by Cursor AI
*& Date: 2026-01-08
*& SAP Version: NetWeaver 7.31
*&---------------------------------------------------------------------*

" BEGIN: Cursor Generated Code

*----------------------------------------------------------------------*
* Type Definitions - Enriched Trip Item
*----------------------------------------------------------------------*
TYPES:
  " Enriched Trip Item with Material and Address fields
  BEGIN OF ty_trip_itm_enr,
    lifnr         TYPE zsce_ctd_itm-lifnr,
    truck_no      TYPE zsce_ctd_itm-truck_no,
    trip_no       TYPE zsce_ctd_itm-trip_no,
    counter       TYPE zsce_ctd_itm-counter,
    shnumber      TYPE zsce_ctd_itm-shnumber,
    source_region TYPE zsce_ctd_itm-source_region,
    dest_region   TYPE zsce_ctd_itm-dest_region,
    material      TYPE matnr,
    adrnr         TYPE adrnr,
    adrnz         TYPE adrnr,
    ctd_eligible  TYPE zsce_ctd_itm-ctd_eligible,
  END OF ty_trip_itm_enr,

  " Table type for enriched items
  tt_trip_itm_enr TYPE STANDARD TABLE OF ty_trip_itm_enr,

  " Shipment number list for bulk operations
  BEGIN OF ty_shnumber,
    shnumber TYPE oig_shnum,
  END OF ty_shnumber,

  tt_shnumber TYPE STANDARD TABLE OF ty_shnumber,

  " Shipment to Delivery mapping (matching OIGSI structure)
  BEGIN OF ty_ship_deliv,
    shnumber   TYPE oig_shnum,
    shitem     TYPE oig_shitm,
    doc_number TYPE oig_docnr,
    doc_typ    TYPE vbtyp,
  END OF ty_ship_deliv,

  tt_ship_deliv TYPE STANDARD TABLE OF ty_ship_deliv,

  " Delivery number list
  BEGIN OF ty_delivery,
    vbeln TYPE vbeln_vl,
  END OF ty_delivery,

  tt_delivery TYPE STANDARD TABLE OF ty_delivery,

  " Delivery to Material mapping (matching LIPS structure)
  BEGIN OF ty_deliv_mat,
    vbeln TYPE lips-vbeln,
    posnr TYPE lips-posnr,
    matnr TYPE lips-matnr,
  END OF ty_deliv_mat,

  tt_deliv_mat TYPE STANDARD TABLE OF ty_deliv_mat,

  " Address number list
  BEGIN OF ty_address,
    addrnumber TYPE adrnr,
  END OF ty_address,

  tt_address TYPE STANDARD TABLE OF ty_address,

  " Address to Region mapping (matching ADRC structure)
  BEGIN OF ty_addr_region,
    addrnumber TYPE adrnr,
    region     TYPE regio,
  END OF ty_addr_region,

  tt_addr_region TYPE STANDARD TABLE OF ty_addr_region,

  " Configuration table structure (matching ZCTD_PROD_REG_RL)
  BEGIN OF ty_config,
    matnr    TYPE matnr,
    region   TYPE regio,
    start_dt TYPE zstart_dt,
    end_date TYPE zend_dt,
  END OF ty_config,

  tt_config TYPE STANDARD TABLE OF ty_config,

  " Validation check structure
  BEGIN OF ty_validation,
    trip_no       TYPE ztrip_no,
    matnr         TYPE matnr,
    source_region TYPE regio,
    dest_region   TYPE regio,
    loaded_legs   TYPE i,
    is_valid      TYPE abap_bool,
    message       TYPE string,
  END OF ty_validation,

  tt_validation TYPE STANDARD TABLE OF ty_validation.

*----------------------------------------------------------------------*
* Constants
*----------------------------------------------------------------------*
CONSTANTS:
  " Rule Status Values
  gc_status_success   TYPE char1 VALUE 'S',
  gc_status_not_appld TYPE char1 VALUE 'N',
  gc_status_error     TYPE char1 VALUE 'E',

  " CTD Eligibility Flag
  gc_ctd_eligible     TYPE char1 VALUE 'X',

  " Trip Status
  gc_trip_stat_exec   TYPE char2 VALUE '08',

  " Document Types for OIGSI
  gc_doc_typ_delivery TYPE vbtyp VALUE 'J',

  " Rule Remarks
  gc_remark_applied   TYPE string VALUE 'Material Region Rule Applied',

  " Messages
  gc_msg_no_loaded    TYPE string VALUE 'No loaded legs found in trip',
  gc_msg_mult_mat     TYPE string VALUE 'Multiple materials found in loaded legs',
  gc_msg_mult_src_reg TYPE string VALUE 'Multiple source regions found in loaded legs',
  gc_msg_mult_dst_reg TYPE string VALUE 'Multiple destination regions found in loaded legs',
  gc_msg_no_config    TYPE string VALUE 'Material-Region combination not found in configuration',
  gc_msg_success      TYPE string VALUE 'Material Region Rule Applied Successfully',

  " Error Messages
  gc_err_oigsi        TYPE string VALUE 'Failed to retrieve delivery numbers from OIGSI',
  gc_err_lips         TYPE string VALUE 'Failed to retrieve materials from LIPS',
  gc_err_adrc_src     TYPE string VALUE 'Failed to retrieve source regions from ADRC',
  gc_err_adrc_dst     TYPE string VALUE 'Failed to retrieve destination regions from ADRC',
  gc_err_config       TYPE string VALUE 'Failed to retrieve CTD configuration data'.

" END: Cursor Generated Code
