*&---------------------------------------------------------------------*
*& Include LZ_CTD_RULES_MATREGF01
*&---------------------------------------------------------------------*
*& Purpose: Subroutines for Material & Region Validation Rule
*& Author: Generated by Cursor AI
*& Date: 2026-01-08
*& SAP Version: NetWeaver 7.31
*&---------------------------------------------------------------------*

" BEGIN: Cursor Generated Code

*&---------------------------------------------------------------------*
*&      Form  IDENTIFY_LOADED_LEGS
*&---------------------------------------------------------------------*
*       Filter loaded legs (SHNUMBER not initial)
*----------------------------------------------------------------------*
*      -->PT_TRIP_ITM     Trip Items table
*      <--PT_LOADED_LEGS  Loaded legs table
*      <--PV_ERROR_FLAG   Error flag
*      <--PV_MESSAGE      Error message
*----------------------------------------------------------------------*
FORM identify_loaded_legs
  TABLES pt_trip_itm     TYPE STANDARD TABLE
         pt_loaded_legs  TYPE tt_trip_itm_enr
  CHANGING pv_error_flag TYPE abap_bool
           pv_message    TYPE string.

  DATA: lw_trip_itm   TYPE zsce_ctd_itm,
        lw_loaded_leg TYPE ty_trip_itm_enr.

  CLEAR: pv_error_flag, pv_message.
  REFRESH pt_loaded_legs.

  LOOP AT pt_trip_itm INTO lw_trip_itm.
    " Check if leg is loaded (has shipment number)
    IF lw_trip_itm-shnumber IS NOT INITIAL.
      CLEAR lw_loaded_leg.
      lw_loaded_leg-lifnr         = lw_trip_itm-lifnr.
      lw_loaded_leg-truck_no      = lw_trip_itm-truck_no.
      lw_loaded_leg-trip_no       = lw_trip_itm-trip_no.
      lw_loaded_leg-counter       = lw_trip_itm-counter.
      lw_loaded_leg-shnumber      = lw_trip_itm-shnumber.
      lw_loaded_leg-source_region = lw_trip_itm-source_region.
      lw_loaded_leg-dest_region   = lw_trip_itm-dest_region.
      lw_loaded_leg-ctd_eligible  = lw_trip_itm-ctd_eligible.

      " Note: material, adrnr, adrnz will be enriched later if needed

      APPEND lw_loaded_leg TO pt_loaded_legs.
    ENDIF.
  ENDLOOP.

  " Check if any loaded legs found
  IF pt_loaded_legs IS INITIAL.
    pv_error_flag = abap_true.
    pv_message = gc_msg_no_loaded.
  ENDIF.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  ENRICH_MATERIAL_DATA
*&---------------------------------------------------------------------*
*       Enrich material information from OIGSI and LIPS
*       OIGSI: Shipment Integration table (SHNUMBER -> DOC_NUMBER)
*       LIPS: Delivery Items table (VBELN -> MATNR)
*----------------------------------------------------------------------*
*      <->PT_LOADED_LEGS  Loaded legs table (updated)
*      <--PV_ERROR_FLAG   Error flag
*      <--PV_MESSAGE      Error message
*----------------------------------------------------------------------*
FORM enrich_material_data
  CHANGING pt_loaded_legs TYPE tt_trip_itm_enr
           pv_error_flag  TYPE abap_bool
           pv_message     TYPE string.

  DATA: lt_shnumbers     TYPE tt_shnumber,
        lw_shnumber      TYPE ty_shnumber,
        lt_ship_deliv    TYPE tt_ship_deliv,
        lw_ship_deliv    TYPE ty_ship_deliv,
        lt_deliveries    TYPE tt_delivery,
        lw_delivery      TYPE ty_delivery,
        lt_deliv_mat     TYPE tt_deliv_mat,
        lw_deliv_mat     TYPE ty_deliv_mat,
        lo_exception     TYPE REF TO cx_root,
        lv_error_text    TYPE string,
        lv_needs_enrich  TYPE abap_bool.

  FIELD-SYMBOLS: <lfs_loaded> TYPE ty_trip_itm_enr.

  CLEAR: pv_error_flag, pv_message.

  " Check if material enrichment is needed
  lv_needs_enrich = abap_false.
  LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>.
    IF <lfs_loaded>-material IS INITIAL.
      lv_needs_enrich = abap_true.
      EXIT.
    ENDIF.
  ENDLOOP.

  CHECK lv_needs_enrich = abap_true.

  TRY.
      " ==============================================================
      " Step 1: Collect shipment numbers requiring enrichment
      " ==============================================================
      REFRESH lt_shnumbers.
      LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>
        WHERE material IS INITIAL.

        CLEAR lw_shnumber.
        lw_shnumber-shnumber = <lfs_loaded>-shnumber.
        APPEND lw_shnumber TO lt_shnumbers.
      ENDLOOP.

      " Remove duplicates
      SORT lt_shnumbers BY shnumber.
      DELETE ADJACENT DUPLICATES FROM lt_shnumbers COMPARING shnumber.

      " ==============================================================
      " Step 2: Fetch Shipment to Delivery mapping from OIGSI
      " ==============================================================
      IF lt_shnumbers IS NOT INITIAL.
        SELECT shnumber shitem doc_number doc_typ
          FROM oigsi
          INTO TABLE lt_ship_deliv
          FOR ALL ENTRIES IN lt_shnumbers
          WHERE shnumber = lt_shnumbers-shnumber
            AND doc_typ = gc_doc_typ_delivery.

        IF sy-subrc <> 0.
          pv_error_flag = abap_true.
          pv_message = gc_err_oigsi.
          RETURN.
        ENDIF.

        " Sort for binary search
        SORT lt_ship_deliv BY shnumber shitem.

        " ==============================================================
        " Step 3: Collect delivery numbers from OIGSI results
        " ==============================================================
        REFRESH lt_deliveries.
        LOOP AT lt_ship_deliv INTO lw_ship_deliv.
          CLEAR lw_delivery.
          lw_delivery-vbeln = lw_ship_deliv-doc_number.
          APPEND lw_delivery TO lt_deliveries.
        ENDLOOP.

        " Remove duplicates
        SORT lt_deliveries BY vbeln.
        DELETE ADJACENT DUPLICATES FROM lt_deliveries COMPARING vbeln.

        " ==============================================================
        " Step 4: Fetch Material from LIPS
        " ==============================================================
        IF lt_deliveries IS NOT INITIAL.
          SELECT vbeln posnr matnr
            FROM lips
            INTO TABLE lt_deliv_mat
            FOR ALL ENTRIES IN lt_deliveries
            WHERE vbeln = lt_deliveries-vbeln
              AND matnr <> space.

          IF sy-subrc <> 0.
            pv_error_flag = abap_true.
            pv_message = gc_err_lips.
            RETURN.
          ENDIF.

          " Sort for binary search
          SORT lt_deliv_mat BY vbeln posnr.
        ENDIF.
      ENDIF.

      " ==============================================================
      " Step 5: Update loaded legs with material information
      " ==============================================================
      LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>
        WHERE material IS INITIAL.

        " Find delivery for this shipment (take first item)
        READ TABLE lt_ship_deliv INTO lw_ship_deliv
          WITH KEY shnumber = <lfs_loaded>-shnumber
          BINARY SEARCH.

        IF sy-subrc = 0.
          " Find material for this delivery (take first item)
          READ TABLE lt_deliv_mat INTO lw_deliv_mat
            WITH KEY vbeln = lw_ship_deliv-doc_number
            BINARY SEARCH.

          IF sy-subrc = 0.
            <lfs_loaded>-material = lw_deliv_mat-matnr.
          ENDIF.
        ENDIF.
      ENDLOOP.

    CATCH cx_root INTO lo_exception.
      lv_error_text = lo_exception->get_text( ).
      pv_error_flag = abap_true.
      CONCATENATE 'Material enrichment error:' lv_error_text
        INTO pv_message SEPARATED BY space.
  ENDTRY.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  ENRICH_REGION_DATA
*&---------------------------------------------------------------------*
*       Enrich source and destination region from ADRC
*       ADRC: Address Master table (ADDRNUMBER -> REGION)
*----------------------------------------------------------------------*
*      <->PT_LOADED_LEGS  Loaded legs table (updated)
*      <--PV_ERROR_FLAG   Error flag
*      <--PV_MESSAGE      Error message
*----------------------------------------------------------------------*
FORM enrich_region_data
  CHANGING pt_loaded_legs TYPE tt_trip_itm_enr
           pv_error_flag  TYPE abap_bool
           pv_message     TYPE string.

  DATA: lt_addresses_src TYPE tt_address,
        lt_addresses_dst TYPE tt_address,
        lw_address       TYPE ty_address,
        lt_addr_region   TYPE tt_addr_region,
        lw_addr_region   TYPE ty_addr_region,
        lo_exception     TYPE REF TO cx_root,
        lv_error_text    TYPE string,
        lv_needs_enrich  TYPE abap_bool.

  FIELD-SYMBOLS: <lfs_loaded> TYPE ty_trip_itm_enr.

  CLEAR: pv_error_flag, pv_message.

  TRY.
      " ===============================================================
      " Enrich Source Region
      " ===============================================================
      lv_needs_enrich = abap_false.
      LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>.
        IF <lfs_loaded>-source_region IS INITIAL.
          lv_needs_enrich = abap_true.
          EXIT.
        ENDIF.
      ENDLOOP.

      IF lv_needs_enrich = abap_true.
        " Collect source addresses
        REFRESH lt_addresses_src.
        LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>
          WHERE source_region IS INITIAL.

          IF <lfs_loaded>-adrnr IS NOT INITIAL.
            CLEAR lw_address.
            lw_address-addrnumber = <lfs_loaded>-adrnr.
            APPEND lw_address TO lt_addresses_src.
          ENDIF.
        ENDLOOP.

        " Remove duplicates
        SORT lt_addresses_src BY addrnumber.
        DELETE ADJACENT DUPLICATES FROM lt_addresses_src
          COMPARING addrnumber.

        " ==============================================================
        " Fetch regions from ADRC
        " ==============================================================
        IF lt_addresses_src IS NOT INITIAL.
          SELECT addrnumber region
            FROM adrc
            INTO TABLE lt_addr_region
            FOR ALL ENTRIES IN lt_addresses_src
            WHERE addrnumber = lt_addresses_src-addrnumber
              AND region <> space
              AND date_from <= sy-datum
              AND date_to >= sy-datum.

          IF sy-subrc <> 0.
            pv_error_flag = abap_true.
            pv_message = gc_err_adrc_src.
            RETURN.
          ENDIF.

          " Sort for binary search
          SORT lt_addr_region BY addrnumber.

          " Update loaded legs
          LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>
            WHERE source_region IS INITIAL.

            READ TABLE lt_addr_region INTO lw_addr_region
              WITH KEY addrnumber = <lfs_loaded>-adrnr
              BINARY SEARCH.

            IF sy-subrc = 0.
              <lfs_loaded>-source_region = lw_addr_region-region.
            ENDIF.
          ENDLOOP.
        ENDIF.
      ENDIF.

      " ===============================================================
      " Enrich Destination Region
      " ===============================================================
      lv_needs_enrich = abap_false.
      LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>.
        IF <lfs_loaded>-dest_region IS INITIAL.
          lv_needs_enrich = abap_true.
          EXIT.
        ENDIF.
      ENDLOOP.

      IF lv_needs_enrich = abap_true.
        " Collect destination addresses
        REFRESH: lt_addresses_dst, lt_addr_region.
        LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>
          WHERE dest_region IS INITIAL.

          IF <lfs_loaded>-adrnz IS NOT INITIAL.
            CLEAR lw_address.
            lw_address-addrnumber = <lfs_loaded>-adrnz.
            APPEND lw_address TO lt_addresses_dst.
          ENDIF.
        ENDLOOP.

        " Remove duplicates
        SORT lt_addresses_dst BY addrnumber.
        DELETE ADJACENT DUPLICATES FROM lt_addresses_dst
          COMPARING addrnumber.

        " ==============================================================
        " Fetch regions from ADRC
        " ==============================================================
        IF lt_addresses_dst IS NOT INITIAL.
          SELECT addrnumber region
            FROM adrc
            INTO TABLE lt_addr_region
            FOR ALL ENTRIES IN lt_addresses_dst
            WHERE addrnumber = lt_addresses_dst-addrnumber
              AND region <> space
              AND date_from <= sy-datum
              AND date_to >= sy-datum.

          IF sy-subrc <> 0.
            pv_error_flag = abap_true.
            pv_message = gc_err_adrc_dst.
            RETURN.
          ENDIF.

          " Sort for binary search
          SORT lt_addr_region BY addrnumber.

          " Update loaded legs
          LOOP AT pt_loaded_legs ASSIGNING <lfs_loaded>
            WHERE dest_region IS INITIAL.

            READ TABLE lt_addr_region INTO lw_addr_region
              WITH KEY addrnumber = <lfs_loaded>-adrnz
              BINARY SEARCH.

            IF sy-subrc = 0.
              <lfs_loaded>-dest_region = lw_addr_region-region.
            ENDIF.
          ENDLOOP.
        ENDIF.
      ENDIF.

    CATCH cx_root INTO lo_exception.
      lv_error_text = lo_exception->get_text( ).
      pv_error_flag = abap_true.
      CONCATENATE 'Region enrichment error:' lv_error_text
        INTO pv_message SEPARATED BY space.
  ENDTRY.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  FETCH_CONFIGURATION
*&---------------------------------------------------------------------*
*       Fetch active Material-Region configurations
*       Table: ZCTD_PROD_REG_RL (CTD Product-Region Rule Configuration)
*----------------------------------------------------------------------*
*      <--PT_CONFIG      Configuration table
*      <--PV_ERROR_FLAG  Error flag
*      <--PV_MESSAGE     Error message
*----------------------------------------------------------------------*
FORM fetch_configuration
  CHANGING pt_config     TYPE tt_config
           pv_error_flag TYPE abap_bool
           pv_message    TYPE string.

  DATA: lo_exception  TYPE REF TO cx_root,
        lv_error_text TYPE string,
        lv_curr_date  TYPE datum.

  CLEAR: pv_error_flag, pv_message.
  REFRESH pt_config.

  lv_curr_date = sy-datum.

  TRY.
      " ==============================================================
      " Fetch active configurations
      " Only records valid for current date
      " ==============================================================
      SELECT matnr region start_dt end_date
        FROM zctd_prod_reg_rl
        INTO TABLE pt_config
        WHERE start_dt <= lv_curr_date
          AND end_date >= lv_curr_date.

      IF sy-subrc <> 0.
        pv_error_flag = abap_true.
        pv_message = gc_msg_no_config.
        RETURN.
      ENDIF.

      " Check if any configurations found
      IF pt_config IS INITIAL.
        pv_error_flag = abap_true.
        pv_message = gc_msg_no_config.
      ELSE.
        " Sort for binary search
        SORT pt_config BY matnr region.
      ENDIF.

    CATCH cx_root INTO lo_exception.
      lv_error_text = lo_exception->get_text( ).
      pv_error_flag = abap_true.
      CONCATENATE gc_err_config lv_error_text
        INTO pv_message SEPARATED BY space.
  ENDTRY.

ENDFORM.

" END: Cursor Generated Code
