*&---------------------------------------------------------------------*
*& Include LZSCE_CTD_RULESTOP
*&---------------------------------------------------------------------*
*& Purpose: Type definitions for CTD Rule Function Group
*& Author: Generated by Cursor AI
*& Date: 2026-01-08
*& SAP Version: NetWeaver 7.31
*&---------------------------------------------------------------------*

" BEGIN: Cursor Generated Code

*----------------------------------------------------------------------*
* Type Definitions - Trip Header
*----------------------------------------------------------------------*
TYPES: BEGIN OF gty_trip_header,
         mandt             TYPE mandt,
         lifnr             TYPE lifnr,
         truck_no          TYPE ytruck_no,
         trip_no           TYPE ztrip_no,
         trip_status       TYPE zctd_trip_st,
         area              TYPE yarea,
         del_ind           TYPE ztrip_delind,
         ctd_ruleeng_remarks TYPE zctd_ruleeng_remarks,
         created_by        TYPE syuname,
         created_date      TYPE sydatum,
         created_time      TYPE systtimlo,
         modified_by       TYPE syuname,
         modified_date     TYPE sydatum,
       END OF gty_trip_header.

TYPES: gty_t_trip_header TYPE STANDARD TABLE OF gty_trip_header
       WITH NON-UNIQUE KEY mandt lifnr truck_no trip_no.

*----------------------------------------------------------------------*
* Type Definitions - Trip Legs
*----------------------------------------------------------------------*
TYPES: BEGIN OF gty_trip_legs,
         mandt             TYPE mandt,
         lifnr             TYPE lifnr,
         truck_no          TYPE ytruck_no,
         trip_no           TYPE ztrip_no,
         counter           TYPE zcounter,
         area              TYPE yarea,
         del_ind           TYPE ztrip_delind,
         shnumber          TYPE oig_shnum,
         shtype            TYPE oig_tdstyp,
         ytts_rep_no       TYPE zytts_rep_no,
         mvt_type          TYPE zctd_mvt_type,
         source_id         TYPE zsource_id2,
         source_date       TYPE zsource_date,
         dest_id           TYPE zdest_id,
         dest_date         TYPE zdest_date,
         ctd_eligible      TYPE zctd_eligible,
         rej_remark        TYPE zctd_remarks,
         rej_code          TYPE yreasoncd,
         source_tzone      TYPE zsource_tzone,
         source_region     TYPE zsource_region,
         dest_tzone        TYPE zdest_tzone,
         dest_region       TYPE zdest_region,
         dest_area         TYPE zdest_area,
         leg_type          TYPE zleg_type,
         source_ent_date   TYPE zsource_ent_date,
         dest_exit_date    TYPE zdest_exit_date,
         route             TYPE zctd_route,
         distance          TYPE zdistance,
       END OF gty_trip_legs.

TYPES: gty_t_trip_legs TYPE STANDARD TABLE OF gty_trip_legs
       WITH NON-UNIQUE KEY mandt lifnr truck_no trip_no counter.

*----------------------------------------------------------------------*
* Type Definitions - Configuration (ZCTD_ERUN_DIS_IC)
*----------------------------------------------------------------------*
TYPES: BEGIN OF gty_config,
         mandt       TYPE mandt,
         legs        TYPE zlegs,
         dist        TYPE zdistance,
         start_dt    TYPE zstart_dt,
         end_date    TYPE zend_dt,
         created_by  TYPE syuname,
         created_on  TYPE sydatum,
         created_at  TYPE systtimlo,
         changed_by  TYPE syuname,
         changed_on  TYPE sydatum,
         changed_at  TYPE systtimlo,
       END OF gty_config.

TYPES: gty_t_config TYPE STANDARD TABLE OF gty_config
       WITH NON-UNIQUE KEY mandt legs start_dt.

*----------------------------------------------------------------------*
* Type Definitions - Working Structures
*----------------------------------------------------------------------*
TYPES: BEGIN OF gty_leg_count,
         trip_no           TYPE ztrip_no,
         loaded_leg_count  TYPE i,
         empty_leg_count   TYPE i,
       END OF gty_leg_count.

TYPES: gty_t_leg_count TYPE STANDARD TABLE OF gty_leg_count
       WITH NON-UNIQUE KEY trip_no.

*----------------------------------------------------------------------*
* Constants
*----------------------------------------------------------------------*
CONSTANTS: gc_status_success        TYPE char2 VALUE '00',
           gc_status_not_applicable TYPE char2 VALUE '01',
           gc_status_error          TYPE char2 VALUE '99',
           gc_trip_status_processed TYPE zctd_trip_st VALUE '08',
           gc_ctd_eligible          TYPE zctd_eligible VALUE 'X',
           gc_sim_mode_active       TYPE char1 VALUE 'X',
           gc_rule_remark           TYPE string
             VALUE 'Empty Run Incentive Distance Rule Applied'.

" END: Cursor Generated Code
