*&---------------------------------------------------------------------*
*& Include LZSCE_CTD_RULESF01
*&---------------------------------------------------------------------*
*& Purpose: Subroutines for CTD Rule Function Group
*& Author: Generated by Cursor AI
*& Date: 2026-01-08
*& SAP Version: NetWeaver 7.31
*&---------------------------------------------------------------------*

" BEGIN: Cursor Generated Code

*&---------------------------------------------------------------------*
*&      Form  F_VALIDATE_INPUT
*&---------------------------------------------------------------------*
*       Validate input parameters
*----------------------------------------------------------------------*
*      -->IT_TRIP_HEADER  Trip Header table
*      -->IT_TRIP_LEGS    Trip Legs table
*      <--CV_MESSAGE      Error message if validation fails
*----------------------------------------------------------------------*
FORM f_validate_input USING it_trip_header TYPE gty_t_trip_header
                            it_trip_legs   TYPE gty_t_trip_legs
                      CHANGING cv_message TYPE string.

  DATA: lw_trip_header TYPE gty_trip_header,
        lw_trip_legs   TYPE gty_trip_legs.

  CLEAR cv_message.

  " Validate Trip Header not empty
  IF it_trip_header IS INITIAL.
    cv_message = 'E001: Trip Header table is empty'.
    RETURN.
  ENDIF.

  " Validate Trip Legs not empty
  IF it_trip_legs IS INITIAL.
    cv_message = 'E002: Trip Legs table is empty'.
    RETURN.
  ENDIF.

  " Validate Trip Start Date and Trip Number
  LOOP AT it_trip_header INTO lw_trip_header.
    IF lw_trip_header-created_date IS INITIAL.
      CONCATENATE 'E003: Invalid Trip Start Date for Trip'
                  lw_trip_header-trip_no
        INTO cv_message SEPARATED BY space.
      RETURN.
    ENDIF.

    IF lw_trip_header-trip_no IS INITIAL.
      cv_message = 'E003: Trip Number cannot be empty'.
      RETURN.
    ENDIF.
  ENDLOOP.

  " Validate Distance values (numeric, non-negative)
  " Note: Validation depends on field type (CHAR vs numeric)
  " This is a placeholder for actual validation

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  F_LOAD_CONFIGURATION
*&---------------------------------------------------------------------*
*       Load configuration from ZCTD_ERUN_DIS_IC
*----------------------------------------------------------------------*
*      <--CT_CONFIG   Configuration table
*      <--CV_MESSAGE  Warning message if no config found
*----------------------------------------------------------------------*
FORM f_load_configuration CHANGING ct_config  TYPE gty_t_config
                                   cv_message TYPE string.

  CLEAR: ct_config, cv_message.

  " Select all active configuration entries
  " Note: ACTIVE_FLAG not in table structure - using date range only
  SELECT mandt legs dist start_dt end_date
         created_by created_on created_at
         changed_by changed_on changed_at
    FROM zctd_erun_dis_ic
    INTO TABLE ct_config
    WHERE mandt = sy-mandt
      AND end_date >= sy-datum.

  IF sy-subrc <> 0.
    " No configuration found - treat as warning
    cv_message = 'W001: No active configuration found in ZCTD_ERUN_DIS_IC'.
    RETURN.
  ENDIF.

  " Sort configuration by LEGS for binary search
  SORT ct_config BY legs start_dt.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  F_COUNT_LEGS
*&---------------------------------------------------------------------*
*       Count Loaded and Empty Legs for a Trip
*----------------------------------------------------------------------*
*      -->IV_TRIP_NO       Trip Number
*      -->IT_TRIP_LEGS     Trip Legs table
*      <--CV_LOADED_COUNT  Count of Loaded Legs
*      <--CV_EMPTY_COUNT   Count of Empty Legs
*----------------------------------------------------------------------*
FORM f_count_legs USING iv_trip_no       TYPE ztrip_no
                        it_trip_legs     TYPE gty_t_trip_legs
                  CHANGING cv_loaded_count TYPE i
                           cv_empty_count  TYPE i.

  DATA: lw_trip_legs TYPE gty_trip_legs.

  CLEAR: cv_loaded_count, cv_empty_count.

  LOOP AT it_trip_legs INTO lw_trip_legs
    WHERE trip_no = iv_trip_no.

    IF lw_trip_legs-shnumber IS NOT INITIAL.
      " Loaded Leg
      cv_loaded_count = cv_loaded_count + 1.
    ELSE.
      " Empty Leg
      cv_empty_count = cv_empty_count + 1.
    ENDIF.

  ENDLOOP.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  F_GET_CONFIGURATION
*&---------------------------------------------------------------------*
*       Get configuration for given Loaded Leg count and date
*----------------------------------------------------------------------*
*      -->IV_LOADED_COUNT     Number of Loaded Legs
*      -->IV_TRIP_START_DATE  Trip Start Date
*      -->IT_CONFIG           Configuration table
*      <--CW_CONFIG           Found configuration entry
*      <--CV_FOUND            Boolean flag indicating if config found
*----------------------------------------------------------------------*
FORM f_get_configuration USING iv_loaded_count    TYPE i
                               iv_trip_start_date TYPE sydatum
                               it_config          TYPE gty_t_config
                         CHANGING cw_config       TYPE gty_config
                                  cv_found        TYPE abap_bool.

  DATA: lv_legs_char TYPE zlegs.

  CLEAR: cw_config, cv_found.

  " Convert integer to character (3 digits with leading zeros)
  lv_legs_char = iv_loaded_count.
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      input  = lv_legs_char
    IMPORTING
      output = lv_legs_char.

  " Search configuration with BINARY SEARCH
  " Configuration is already sorted by LEGS
  READ TABLE it_config INTO cw_config
    WITH KEY legs = lv_legs_char
    BINARY SEARCH.

  IF sy-subrc = 0.
    " Found entry - validate date range
    IF iv_trip_start_date >= cw_config-start_dt AND
       iv_trip_start_date <= cw_config-end_date.
      cv_found = abap_true.
    ELSE.
      CLEAR cw_config.
      cv_found = abap_false.
    ENDIF.
  ELSE.
    cv_found = abap_false.
  ENDIF.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  F_EVALUATE_EMPTY_LEGS
*&---------------------------------------------------------------------*
*       Evaluate if any Empty Leg exceeds Incentive Distance
*----------------------------------------------------------------------*
*      -->IV_TRIP_NO         Trip Number
*      -->IV_INCENTIVE_DIST  Incentive Distance threshold
*      -->IT_TRIP_LEGS       Trip Legs table
*      <--CV_RULE_APPLIED    Boolean flag indicating if rule applies
*----------------------------------------------------------------------*
FORM f_evaluate_empty_legs USING iv_trip_no        TYPE ztrip_no
                                 iv_incentive_dist TYPE zdistance
                                 it_trip_legs      TYPE gty_t_trip_legs
                           CHANGING cv_rule_applied TYPE abap_bool.

  DATA: lw_trip_legs      TYPE gty_trip_legs,
        lv_leg_distance   TYPE zdistance,
        lv_incentive_num  TYPE p DECIMALS 2,
        lv_distance_num   TYPE p DECIMALS 2.

  CLEAR cv_rule_applied.

  " Convert incentive distance to numeric (if CHAR type)
  lv_incentive_num = iv_incentive_dist.

  LOOP AT it_trip_legs INTO lw_trip_legs
    WHERE trip_no = iv_trip_no
      AND shnumber IS INITIAL.

    lv_leg_distance = lw_trip_legs-distance.
    lv_distance_num = lv_leg_distance.

    " Check if distance exceeds incentive threshold
    IF lv_distance_num > lv_incentive_num.
      cv_rule_applied = abap_true.
      EXIT.  " Early exit - one qualifying leg is enough
    ENDIF.

  ENDLOOP.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  F_UPDATE_LOADED_LEGS
*&---------------------------------------------------------------------*
*       Update all Loaded Legs with CTD Eligibility flag
*----------------------------------------------------------------------*
*      -->IV_TRIP_NO    Trip Number
*      <->CT_TRIP_LEGS  Trip Legs table (updated)
*----------------------------------------------------------------------*
FORM f_update_loaded_legs USING iv_trip_no   TYPE ztrip_no
                          CHANGING ct_trip_legs TYPE gty_t_trip_legs.

  FIELD-SYMBOLS: <lfs_trip_legs> TYPE gty_trip_legs.

  LOOP AT ct_trip_legs ASSIGNING <lfs_trip_legs>
    WHERE trip_no = iv_trip_no
      AND shnumber IS NOT INITIAL.

    <lfs_trip_legs>-ctd_eligible = gc_ctd_eligible.

  ENDLOOP.

ENDFORM.

" END: Cursor Generated Code
