*&---------------------------------------------------------------------*
*& Include ZCTD_RULEENG_EXECSEL
*&---------------------------------------------------------------------*
*& Purpose: Selection screen parameters
*& Author: Generated by Cursor AI
*& Date: 2026-01-16
*&---------------------------------------------------------------------*

*----------------------------------------------------------------------*
* Selection Screen
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-001.

  " Selection Criteria
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(25) text-002.
  SELECTION-SCREEN END OF LINE.

  PARAMETERS: p_fdate TYPE sydatum OBLIGATORY.
  PARAMETERS: p_tdate TYPE sydatum OBLIGATORY DEFAULT sy-datum.

  SELECTION-SCREEN SKIP 1.

  " Execution Mode
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(25) text-003.
  SELECTION-SCREEN END OF LINE.

  PARAMETERS: p_fgnd  AS CHECKBOX DEFAULT 'X'.
  PARAMETERS: p_bgnd  AS CHECKBOX.
  PARAMETERS: p_simul AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK b1.

*----------------------------------------------------------------------*
* Text Symbols
*----------------------------------------------------------------------*
* TEXT-001: 'CTD Rule Engine Execution'
* TEXT-002: 'Selection Criteria'
* TEXT-003: 'Execution Mode'
