*&---------------------------------------------------------------------*
*& Include ZCTD_RULEENG_EXECTOP
*&---------------------------------------------------------------------*
*& Purpose: Global type definitions and data declarations
*& Author: Generated by Cursor AI
*& Date: 2026-01-16
*&---------------------------------------------------------------------*

*----------------------------------------------------------------------*
* Type Definitions - Trip Processing
*----------------------------------------------------------------------*
TYPES:
  " Trip Header with RuleMap info
  BEGIN OF gty_trip_proc,
    lifnr             TYPE zsce_ctd_hdr-lifnr,
    truck_no          TYPE zsce_ctd_hdr-truck_no,
    trip_no           TYPE zsce_ctd_hdr-trip_no,
    trip_status       TYPE zsce_ctd_hdr-trip_status,
    prev_status       TYPE zsce_ctd_hdr-trip_status,
    business_id       TYPE char10,
    sub_business_id   TYPE char10,
    rulemap_id        TYPE char20,
    created_date      TYPE zsce_ctd_hdr-created_date,
    ctd_ruleeng_remarks TYPE zsce_ctd_hdr-ctd_ruleeng_remarks,
    exec_status       TYPE char10,
    exec_message      TYPE string,
    processed_on      TYPE timestamp,
  END OF gty_trip_proc,

  gty_t_trip_proc TYPE STANDARD TABLE OF gty_trip_proc,

  " RuleMap Determination
  BEGIN OF gty_rulemap_det,
    business_id     TYPE char10,
    sub_business_id TYPE char10,
    rulemap_id      TYPE char20,
    priority        TYPE int4,
    active          TYPE char1,
    start_date      TYPE sydatum,
    end_date        TYPE sydatum,
  END OF gty_rulemap_det,

  gty_t_rulemap_det TYPE STANDARD TABLE OF gty_rulemap_det,

  " RuleMap Process Configuration
  BEGIN OF gty_rulemap_proc,
    rulemap_id      TYPE char20,
    process_type    TYPE char10,
    seq_no          TYPE numc3,
    fm_name         TYPE funcname,
    exec_condition  TYPE char255,
    active          TYPE char1,
    description     TYPE char60,
  END OF gty_rulemap_proc,

  gty_t_rulemap_proc TYPE STANDARD TABLE OF gty_rulemap_proc,

  " Rule Execution Result
  BEGIN OF gty_rule_result,
    trip_no         TYPE zsce_ctd_hdr-trip_no,
    rulemap_id      TYPE char20,
    rule_seq        TYPE numc3,
    rule_fm         TYPE funcname,
    rule_status     TYPE char1,
    rule_message    TYPE string,
    exec_timestamp  TYPE timestamp,
  END OF gty_rule_result,

  gty_t_rule_result TYPE STANDARD TABLE OF gty_rule_result,

  " ALV Display Structure
  BEGIN OF gty_alv_output,
    trip_no         TYPE zsce_ctd_hdr-trip_no,
    lifnr           TYPE lifnr,
    truck_no        TYPE ytruck_no,
    rulemap_id      TYPE char20,
    rule_seq        TYPE string,
    prev_status     TYPE zctd_trip_st,
    new_status      TYPE zctd_trip_st,
    ctd_eligible    TYPE zctd_eligible,
    exec_status     TYPE char10,
    exec_message    TYPE string,
    processed_on    TYPE char20,
  END OF gty_alv_output,

  gty_t_alv_output TYPE STANDARD TABLE OF gty_alv_output.

*----------------------------------------------------------------------*
* Type Definitions - Database Tables
*----------------------------------------------------------------------*
TYPES:
  gty_t_trip_hdr TYPE STANDARD TABLE OF zsce_ctd_hdr,
  gty_t_trip_itm TYPE STANDARD TABLE OF zsce_ctd_itm.

*----------------------------------------------------------------------*
* Global Data Declarations
*----------------------------------------------------------------------*
DATA:
  " Processing Tables
  gt_trip_hdr       TYPE gty_t_trip_hdr,
  gt_trip_itm       TYPE gty_t_trip_itm,
  gt_trip_proc      TYPE gty_t_trip_proc,
  gt_rulemap_det    TYPE gty_t_rulemap_det,
  gt_rulemap_proc   TYPE gty_t_rulemap_proc,
  gt_rule_result    TYPE gty_t_rule_result,
  gt_alv_output     TYPE gty_t_alv_output,

  " Working Variables
  gv_trips_fetched  TYPE i,
  gv_trips_proc     TYPE i,
  gv_trips_eligible TYPE i,
  gv_trips_error    TYPE i,
  gv_start_time     TYPE timestamp,
  gv_end_time       TYPE timestamp,
  gv_runtime        TYPE i,

  " Application Log
  gv_log_handle     TYPE balloghndl,

  " ALV Grid Object
  go_alv_grid       TYPE REF TO cl_gui_alv_grid,
  go_custom_cont    TYPE REF TO cl_gui_custom_container.

*----------------------------------------------------------------------*
* Constants
*----------------------------------------------------------------------*
CONSTANTS:
  " Trip Status Values
  gc_stat_confirmed TYPE zctd_trip_st VALUE '07',
  gc_stat_executed  TYPE zctd_trip_st VALUE '08',
  gc_stat_error     TYPE zctd_trip_st VALUE 'E0',

  " Process Types
  gc_proc_elig_rule TYPE char10 VALUE 'ELIG_RULE',
  gc_proc_calc      TYPE char10 VALUE 'CALC',

  " Rule Status Values
  gc_rule_success   TYPE char1 VALUE 'S',
  gc_rule_not_appld TYPE char1 VALUE 'N',
  gc_rule_error     TYPE char1 VALUE 'E',

  " Execution Status
  gc_exec_success   TYPE char10 VALUE 'SUCCESS',
  gc_exec_partial   TYPE char10 VALUE 'PARTIAL',
  gc_exec_warning   TYPE char10 VALUE 'WARNING',
  gc_exec_error     TYPE char10 VALUE 'ERROR',
  gc_exec_skipped   TYPE char10 VALUE 'SKIPPED',

  " Messages
  gc_msg_no_trips   TYPE string VALUE 'No eligible trips found for selected date range',
  gc_msg_no_rulemap TYPE string VALUE 'No active RuleMap found',
  gc_msg_no_rules   TYPE string VALUE 'No eligibility rules configured',
  gc_msg_rule_exec  TYPE string VALUE 'Rule execution completed',
  gc_msg_db_error   TYPE string VALUE 'Database update failed',

  " Application Log
  gc_log_object     TYPE balobj_d VALUE 'ZCTD_RENG',
  gc_log_subobject  TYPE balsubobj VALUE 'EXEC',

  " Field Lengths
  gc_max_remarks    TYPE i VALUE 255.
