*&---------------------------------------------------------------------*
*& Report ZCTD_RULEENG_EXEC
*&---------------------------------------------------------------------*
*& Purpose: CTD Rule Engine - Configuration-Driven Orchestrator
*& Description: Executes CTD eligibility rules based on RuleMap config
*& Author: Generated by Cursor AI
*& Date: 2026-01-16
*& SAP Version: NetWeaver 7.31
*&---------------------------------------------------------------------*
REPORT zctd_ruleeng_exec.

*----------------------------------------------------------------------*
* Include Files
*----------------------------------------------------------------------*
INCLUDE zctd_ruleeng_exectop.    " Global declarations
INCLUDE zctd_ruleeng_execsel.    " Selection screen
INCLUDE zctd_ruleeng_execc01.    " Classes - All logic here

*----------------------------------------------------------------------*
* Global Objects
*----------------------------------------------------------------------*
DATA: go_report TYPE REF TO lcl_report.

*----------------------------------------------------------------------*
* Initialization
*----------------------------------------------------------------------*
INITIALIZATION.
  CREATE OBJECT go_report.
  go_report->initialization( ).

*----------------------------------------------------------------------*
* At Selection Screen
*----------------------------------------------------------------------*
AT SELECTION-SCREEN.
  CREATE OBJECT go_report.
  go_report->validate_selection_screen( ).

*----------------------------------------------------------------------*
* Start of Selection
*----------------------------------------------------------------------*
START-OF-SELECTION.
  CREATE OBJECT go_report.
  go_report->main_processing( ).

*----------------------------------------------------------------------*
* End of Selection
*----------------------------------------------------------------------*
END-OF-SELECTION.
  go_report->display_results( ).
