FUNCTION zsce_ctd_erundis_rule.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IV_SIMULATION_MODE) TYPE  CHAR1 DEFAULT SPACE
*"  EXPORTING
*"     VALUE(EV_STATUS) TYPE  CHAR2
*"     VALUE(EV_MESSAGE) TYPE  STRING
*"     VALUE(EV_TRIPS_PROCESSED) TYPE  I
*"     VALUE(EV_TRIPS_QUALIFIED) TYPE  I
*"  TABLES
*"      IT_TRIP_HEADER TYPE  GTY_T_TRIP_HEADER
*"      IT_TRIP_LEGS TYPE  GTY_T_TRIP_LEGS
*"  CHANGING
*"     VALUE(CT_TRIP_HEADER) TYPE  GTY_T_TRIP_HEADER
*"     VALUE(CT_TRIP_LEGS) TYPE  GTY_T_TRIP_LEGS
*"  EXCEPTIONS
*"      CONFIGURATION_ERROR
*"      DATA_INCONSISTENCY
*"      TECHNICAL_ERROR
*"----------------------------------------------------------------------
*&---------------------------------------------------------------------*
*& Function Module: ZSCE_CTD_ERUNDIS_RULE
*&---------------------------------------------------------------------*
*& Purpose: CTD Rule 2 - Empty Run Incentive Distance Rule
*& Description: Determines CTD eligibility based on Empty Run Distance
*&              exceeding configured incentive thresholds
*& Author: Generated by Cursor AI
*& Date: 2026-01-08
*& SAP Version: NetWeaver 7.31
*&---------------------------------------------------------------------*

  " BEGIN: Cursor Generated Code

  " ======================================================================
  " Variable Declarations
  " ======================================================================
  DATA: lt_config           TYPE gty_t_config,
        lw_trip_header      TYPE gty_trip_header,
        lw_trip_legs        TYPE gty_trip_legs,
        lw_config           TYPE gty_config,
        lv_loaded_count     TYPE i,
        lv_empty_count      TYPE i,
        lv_trip_start_date  TYPE sydatum,
        lv_incentive_dist   TYPE zdistance,
        lv_trips_processed  TYPE i,
        lv_trips_qualified  TYPE i,
        lv_rule_applied     TYPE abap_bool,
        lv_config_found     TYPE abap_bool,
        lv_legs_char        TYPE zlegs,
        lv_message          TYPE string,
        lo_exception        TYPE REF TO cx_root,
        lv_error_text       TYPE string.

  FIELD-SYMBOLS: <lfs_trip_header> TYPE gty_trip_header,
                 <lfs_trip_legs>   TYPE gty_trip_legs.

  " ======================================================================
  " Initialize Export Parameters
  " ======================================================================
  CLEAR: ev_status,
         ev_message,
         ev_trips_processed,
         ev_trips_qualified.

  lv_trips_processed = 0.
  lv_trips_qualified = 0.

  TRY.
      " ==================================================================
      " Step 1: Input Validation
      " ==================================================================
      PERFORM f_validate_input USING it_trip_header
                                      it_trip_legs
                               CHANGING lv_message.

      IF lv_message IS NOT INITIAL.
        ev_status = gc_status_error.
        ev_message = lv_message.
        RAISE data_inconsistency.
      ENDIF.

      " ==================================================================
      " Step 2: Load Configuration (Performance Optimization)
      " ==================================================================
      PERFORM f_load_configuration CHANGING lt_config
                                            lv_message.

      IF lv_message IS NOT INITIAL.
        ev_status = gc_status_error.
        ev_message = lv_message.
        RAISE configuration_error.
      ENDIF.

      " ==================================================================
      " Step 3: Copy Input Tables to Changing Parameters
      " ==================================================================
      ct_trip_header[] = it_trip_header[].
      ct_trip_legs[] = it_trip_legs[].

      " ==================================================================
      " Step 4: Process Each Trip
      " ==================================================================
      LOOP AT ct_trip_header ASSIGNING <lfs_trip_header>.

        " Skip if Trip already processed (Status = '08')
        IF <lfs_trip_header>-trip_status = gc_trip_status_processed.
          CONTINUE.
        ENDIF.

        CLEAR: lv_loaded_count,
               lv_empty_count,
               lv_rule_applied,
               lv_config_found.

        lv_trip_start_date = <lfs_trip_header>-created_date.

        " ----------------------------------------------------------------
        " Step 4.1: Count Loaded and Empty Legs
        " ----------------------------------------------------------------
        PERFORM f_count_legs USING <lfs_trip_header>-trip_no
                                   ct_trip_legs
                            CHANGING lv_loaded_count
                                     lv_empty_count.

        " ----------------------------------------------------------------
        " Step 4.2: Skip if no Loaded or Empty Legs
        " ----------------------------------------------------------------
        IF lv_loaded_count = 0 OR lv_empty_count = 0.
          " Rule not applicable for this Trip
          CONTINUE.
        ENDIF.

        " ----------------------------------------------------------------
        " Step 4.3: Find Configuration
        " ----------------------------------------------------------------
        PERFORM f_get_configuration USING lv_loaded_count
                                          lv_trip_start_date
                                          lt_config
                                   CHANGING lw_config
                                            lv_config_found.

        IF lv_config_found = abap_false.
          " No configuration found for this Loaded Leg count
          CONTINUE.
        ENDIF.

        lv_incentive_dist = lw_config-dist.

        " ----------------------------------------------------------------
        " Step 4.4: Evaluate Empty Leg Distances
        " ----------------------------------------------------------------
        PERFORM f_evaluate_empty_legs USING <lfs_trip_header>-trip_no
                                             lv_incentive_dist
                                             ct_trip_legs
                                      CHANGING lv_rule_applied.

        " ----------------------------------------------------------------
        " Step 4.5: Update CTD Eligibility if Rule Applied
        " ----------------------------------------------------------------
        IF lv_rule_applied = abap_true.

          " Update all Loaded Legs: CTD_ELIGIBLE = 'X'
          PERFORM f_update_loaded_legs USING <lfs_trip_header>-trip_no
                                       CHANGING ct_trip_legs.

          " Update Trip Header: Status and Remarks
          <lfs_trip_header>-trip_status = gc_trip_status_processed.
          <lfs_trip_header>-ctd_ruleeng_remarks = gc_rule_remark.
          <lfs_trip_header>-modified_by = sy-uname.
          <lfs_trip_header>-modified_date = sy-datum.

          lv_trips_qualified = lv_trips_qualified + 1.

        ENDIF.

        lv_trips_processed = lv_trips_processed + 1.

      ENDLOOP.

      " ==================================================================
      " Step 5: Set Export Parameters
      " ==================================================================
      ev_trips_processed = lv_trips_processed.
      ev_trips_qualified = lv_trips_qualified.

      IF lv_trips_qualified > 0.
        ev_status = gc_status_success.
        CONCATENATE 'Rule applied successfully.'
                    lv_trips_qualified
                    'Trip(s) qualified for CTD'
          INTO ev_message SEPARATED BY space.
      ELSE.
        ev_status = gc_status_not_applicable.
        ev_message = 'Rule not applicable - No Trips qualified'.
      ENDIF.

    CATCH cx_root INTO lo_exception.
      " ==================================================================
      " Exception Handling
      " ==================================================================
      lv_error_text = lo_exception->get_text( ).
      ev_status = gc_status_error.
      ev_message = lv_error_text.
      RAISE technical_error.

  ENDTRY.

  " END: Cursor Generated Code

ENDFUNCTION.
