FUNCTION zsce_ctd_matregval_rule.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IV_SIMULATION_MODE) TYPE  ABAP_BOOL DEFAULT ABAP_FALSE
*"  TABLES
*"      IT_TRIP_HDR STRUCTURE  ZSCE_CTD_HDR
*"      IT_TRIP_ITM STRUCTURE  ZSCE_CTD_ITM
*"      ET_TRIP_HDR STRUCTURE  ZSCE_CTD_HDR
*"      ET_TRIP_ITM STRUCTURE  ZSCE_CTD_ITM
*"  EXPORTING
*"     REFERENCE(EV_RULE_STATUS) TYPE  CHAR1
*"     REFERENCE(EV_RULE_MESSAGE) TYPE  STRING
*"     REFERENCE(EV_TRIPS_PROCESSED) TYPE  I
*"     REFERENCE(EV_TRIPS_ELIGIBLE) TYPE  I
*"  EXCEPTIONS
*"      SYSTEM_ERROR
*"----------------------------------------------------------------------
*&---------------------------------------------------------------------*
*& Function Module: ZSCE_CTD_MATREGVAL_RULE
*&---------------------------------------------------------------------*
*& Purpose: CTD Rule - Material & Region Validation
*& Description: Validates Material and Region consistency for CTD
*&              eligibility determination
*& Author: Generated by Cursor AI
*& Date: 2026-01-08
*& SAP Version: NetWeaver 7.31
*&
*& Database Tables Used:
*&   - OIGSI: Shipment Integration (SHNUMBER -> DOC_NUMBER)
*&   - LIPS: Delivery Items (VBELN -> MATNR)
*&   - ADRC: Address Master (ADDRNUMBER -> REGION)
*&   - ZCTD_PROD_REG_RL: Material-Region Configuration
*&---------------------------------------------------------------------*

  " BEGIN: Cursor Generated Code

  " ===================================================================
  " Data Declarations
  " ===================================================================
  DATA: lt_loaded_legs     TYPE tt_trip_itm_enr,
        lt_ship_deliv      TYPE tt_ship_deliv,
        lt_deliv_mat       TYPE tt_deliv_mat,
        lt_addr_region_src TYPE tt_addr_region,
        lt_addr_region_dst TYPE tt_addr_region,
        lt_config          TYPE tt_config,
        lt_validation      TYPE tt_validation,
        lw_trip_hdr        TYPE zsce_ctd_hdr,
        lw_trip_itm        TYPE zsce_ctd_itm,
        lw_loaded_leg      TYPE ty_trip_itm_enr,
        lw_validation      TYPE ty_validation,
        lv_matnr           TYPE matnr,
        lv_src_region      TYPE regio,
        lv_dst_region      TYPE regio,
        lv_cnt_matnr       TYPE i,
        lv_cnt_src         TYPE i,
        lv_cnt_dst         TYPE i,
        lv_error_flag      TYPE abap_bool,
        lo_exception       TYPE REF TO cx_root,
        lv_error_text      TYPE string.

  FIELD-SYMBOLS: <lfs_trip_hdr> TYPE zsce_ctd_hdr,
                 <lfs_trip_itm> TYPE zsce_ctd_itm,
                 <lfs_loaded>   TYPE ty_trip_itm_enr.

  " ===================================================================
  " Initialize
  " ===================================================================
  CLEAR: ev_rule_status,
         ev_rule_message,
         ev_trips_processed,
         ev_trips_eligible.

  " Copy input tables to output tables
  REFRESH: et_trip_hdr, et_trip_itm.
  et_trip_hdr[] = it_trip_hdr[].
  et_trip_itm[] = it_trip_itm[].

  TRY.
      " ==================================================================
      " Step 1: Identify Loaded Legs
      " ==================================================================
      PERFORM identify_loaded_legs
        TABLES et_trip_itm
               lt_loaded_legs
        CHANGING lv_error_flag
                 ev_rule_message.

      IF lv_error_flag = abap_true.
        ev_rule_status = gc_status_not_appld.
        RETURN.
      ENDIF.

      " ==================================================================
      " Step 2: Data Enrichment - Material
      " ==================================================================
      PERFORM enrich_material_data
        CHANGING lt_loaded_legs
                 lv_error_flag
                 ev_rule_message.

      IF lv_error_flag = abap_true.
        ev_rule_status = gc_status_error.
        RAISE system_error.
      ENDIF.

      " ==================================================================
      " Step 3: Data Enrichment - Region
      " ==================================================================
      PERFORM enrich_region_data
        CHANGING lt_loaded_legs
                 lv_error_flag
                 ev_rule_message.

      IF lv_error_flag = abap_true.
        ev_rule_status = gc_status_error.
        RAISE system_error.
      ENDIF.

      " ==================================================================
      " Step 4: Fetch Configuration
      " ==================================================================
      PERFORM fetch_configuration
        CHANGING lt_config
                 lv_error_flag
                 ev_rule_message.

      IF lv_error_flag = abap_true.
        ev_rule_status = gc_status_error.
        RAISE system_error.
      ENDIF.

      " ==================================================================
      " Step 5: Validate Material & Region Consistency
      " ==================================================================
      PERFORM validate_material_region
        TABLES lt_loaded_legs
               lt_config
        CHANGING lt_validation
                 lv_error_flag
                 ev_rule_message.

      IF lv_error_flag = abap_true.
        ev_rule_status = gc_status_not_appld.
        RETURN.
      ENDIF.

      " ==================================================================
      " Step 6: Update CTD Eligibility
      " ==================================================================
      PERFORM update_ctd_eligibility
        TABLES lt_validation
        CHANGING et_trip_hdr
                 et_trip_itm
                 ev_trips_processed
                 ev_trips_eligible.

      " ==================================================================
      " Set Success Status
      " ==================================================================
      IF ev_trips_eligible > 0.
        ev_rule_status = gc_status_success.
        ev_rule_message = gc_msg_success.
      ELSE.
        ev_rule_status = gc_status_not_appld.
      ENDIF.

    CATCH cx_root INTO lo_exception.
      lv_error_text = lo_exception->get_text( ).
      ev_rule_status = gc_status_error.
      CONCATENATE 'System error:' lv_error_text
        INTO ev_rule_message SEPARATED BY space.
      RAISE system_error.

  ENDTRY.

  " END: Cursor Generated Code

ENDFUNCTION.
