*&---------------------------------------------------------------------*
*& Report  ZTEST_CTD_ERUNDIS_RULE
*&---------------------------------------------------------------------*
*& Purpose: Unit test for ZSCE_CTD_ERUNDIS_RULE
*& Author: Generated by Cursor AI
*& Date: 2026-01-08
*& SAP Version: NetWeaver 7.31
*&---------------------------------------------------------------------*
REPORT ztest_ctd_erundis_rule.

" BEGIN: Cursor Generated Code

*----------------------------------------------------------------------*
* Type Definitions (reuse from function group TOP)
*----------------------------------------------------------------------*
INCLUDE lzsce_ctd_rulestop.

*----------------------------------------------------------------------*
* Test Data
*----------------------------------------------------------------------*
DATA: gt_trip_header_in  TYPE gty_t_trip_header,
      gt_trip_legs_in    TYPE gty_t_trip_legs,
      gt_trip_header_out TYPE gty_t_trip_header,
      gt_trip_legs_out   TYPE gty_t_trip_legs,
      gv_status          TYPE char2,
      gv_message         TYPE string,
      gv_trips_processed TYPE i,
      gv_trips_qualified TYPE i.

*----------------------------------------------------------------------*
* Selection Screen
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-001.
PARAMETERS: p_test TYPE i DEFAULT 1.
SELECTION-SCREEN END OF BLOCK b1.

*----------------------------------------------------------------------*
* Initialization
*----------------------------------------------------------------------*
INITIALIZATION.
  " Set text elements
  text-001 = 'Test Case Selection'.

*----------------------------------------------------------------------*
* Main Processing
*----------------------------------------------------------------------*
START-OF-SELECTION.

  CASE p_test.
    WHEN 1.
      PERFORM test_case_01.
    WHEN 2.
      PERFORM test_case_02.
    WHEN 3.
      PERFORM test_case_03.
    WHEN 4.
      PERFORM test_case_04.
    WHEN OTHERS.
      WRITE: / 'Invalid test case number'.
      WRITE: / 'Valid test cases: 1-4'.
  ENDCASE.

*&---------------------------------------------------------------------*
*&      Form  TEST_CASE_01
*&---------------------------------------------------------------------*
*       Test Case 01: Trip qualifies for CTD
*       - 1 Loaded Leg, 1 Empty Leg exceeding threshold
*----------------------------------------------------------------------*
FORM test_case_01.

  DATA: lw_header TYPE gty_trip_header,
        lw_legs   TYPE gty_trip_legs.

  WRITE: / 'Test Case 01: Trip qualifies for CTD'.
  WRITE: / '========================================'.

  " Prepare test data
  CLEAR: gt_trip_header_in, gt_trip_legs_in.

  " Trip Header
  lw_header-mandt = sy-mandt.
  lw_header-lifnr = 'V00001'.
  lw_header-truck_no = 'TRK001'.
  lw_header-trip_no = 'TRP0000000001'.
  lw_header-trip_status = '01'.
  lw_header-created_date = sy-datum.
  APPEND lw_header TO gt_trip_header_in.

  " Leg 1: Loaded
  lw_legs-mandt = sy-mandt.
  lw_legs-lifnr = 'V00001'.
  lw_legs-truck_no = 'TRK001'.
  lw_legs-trip_no = 'TRP0000000001'.
  lw_legs-counter = '01'.
  lw_legs-shnumber = 'SH001'.
  lw_legs-distance = '0100'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Leg 2: Empty (exceeds threshold of 50)
  lw_legs-counter = '02'.
  lw_legs-shnumber = ''.
  lw_legs-distance = '0075'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Call function module
  CALL FUNCTION 'ZSCE_CTD_ERUNDIS_RULE'
    EXPORTING
      iv_simulation_mode = 'X'
    IMPORTING
      ev_status          = gv_status
      ev_message         = gv_message
      ev_trips_processed = gv_trips_processed
      ev_trips_qualified = gv_trips_qualified
    TABLES
      it_trip_header     = gt_trip_header_in
      it_trip_legs       = gt_trip_legs_in
    CHANGING
      ct_trip_header     = gt_trip_header_out
      ct_trip_legs       = gt_trip_legs_out
    EXCEPTIONS
      configuration_error = 1
      data_inconsistency  = 2
      technical_error     = 3
      OTHERS              = 4.

  IF sy-subrc <> 0.
    WRITE: / 'Test Case 01 FAILED: Exception raised', sy-subrc.
  ELSE.
    WRITE: / 'Results:'.
    WRITE: / '  Status:', gv_status.
    WRITE: / '  Message:', gv_message.
    WRITE: / '  Trips Processed:', gv_trips_processed.
    WRITE: / '  Trips Qualified:', gv_trips_qualified.

    " Verify results
    IF gv_status = '00' AND gv_trips_qualified = 1.
      WRITE: / 'Test Case 01 PASSED', icon_led_green AS ICON.
    ELSE.
      WRITE: / 'Test Case 01 FAILED', icon_led_red AS ICON.
    ENDIF.
  ENDIF.

  SKIP 2.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  TEST_CASE_02
*&---------------------------------------------------------------------*
*       Test Case 02: Trip does not qualify
*       - Empty Leg distance below threshold
*----------------------------------------------------------------------*
FORM test_case_02.

  DATA: lw_header TYPE gty_trip_header,
        lw_legs   TYPE gty_trip_legs.

  WRITE: / 'Test Case 02: Trip does not qualify'.
  WRITE: / '========================================'.

  " Prepare test data
  CLEAR: gt_trip_header_in, gt_trip_legs_in.

  " Trip Header
  lw_header-mandt = sy-mandt.
  lw_header-lifnr = 'V00002'.
  lw_header-truck_no = 'TRK002'.
  lw_header-trip_no = 'TRP0000000002'.
  lw_header-trip_status = '01'.
  lw_header-created_date = sy-datum.
  APPEND lw_header TO gt_trip_header_in.

  " Leg 1: Loaded
  lw_legs-mandt = sy-mandt.
  lw_legs-lifnr = 'V00002'.
  lw_legs-truck_no = 'TRK002'.
  lw_legs-trip_no = 'TRP0000000002'.
  lw_legs-counter = '01'.
  lw_legs-shnumber = 'SH002'.
  lw_legs-distance = '0100'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Leg 2: Empty (below threshold of 50)
  lw_legs-counter = '02'.
  lw_legs-shnumber = ''.
  lw_legs-distance = '0040'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Call function module
  CALL FUNCTION 'ZSCE_CTD_ERUNDIS_RULE'
    EXPORTING
      iv_simulation_mode = 'X'
    IMPORTING
      ev_status          = gv_status
      ev_message         = gv_message
      ev_trips_processed = gv_trips_processed
      ev_trips_qualified = gv_trips_qualified
    TABLES
      it_trip_header     = gt_trip_header_in
      it_trip_legs       = gt_trip_legs_in
    CHANGING
      ct_trip_header     = gt_trip_header_out
      ct_trip_legs       = gt_trip_legs_out
    EXCEPTIONS
      configuration_error = 1
      data_inconsistency  = 2
      technical_error     = 3
      OTHERS              = 4.

  IF sy-subrc <> 0.
    WRITE: / 'Test Case 02 FAILED: Exception raised', sy-subrc.
  ELSE.
    WRITE: / 'Results:'.
    WRITE: / '  Status:', gv_status.
    WRITE: / '  Message:', gv_message.
    WRITE: / '  Trips Processed:', gv_trips_processed.
    WRITE: / '  Trips Qualified:', gv_trips_qualified.

    " Verify results - should not qualify
    IF gv_status = '01' AND gv_trips_qualified = 0.
      WRITE: / 'Test Case 02 PASSED', icon_led_green AS ICON.
    ELSE.
      WRITE: / 'Test Case 02 FAILED', icon_led_red AS ICON.
    ENDIF.
  ENDIF.

  SKIP 2.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  TEST_CASE_03
*&---------------------------------------------------------------------*
*       Test Case 03: Trip with only Loaded Legs (no Empty Legs)
*----------------------------------------------------------------------*
FORM test_case_03.

  DATA: lw_header TYPE gty_trip_header,
        lw_legs   TYPE gty_trip_legs.

  WRITE: / 'Test Case 03: Trip with only Loaded Legs'.
  WRITE: / '========================================'.

  " Prepare test data
  CLEAR: gt_trip_header_in, gt_trip_legs_in.

  " Trip Header
  lw_header-mandt = sy-mandt.
  lw_header-lifnr = 'V00003'.
  lw_header-truck_no = 'TRK003'.
  lw_header-trip_no = 'TRP0000000003'.
  lw_header-trip_status = '01'.
  lw_header-created_date = sy-datum.
  APPEND lw_header TO gt_trip_header_in.

  " Leg 1: Loaded
  lw_legs-mandt = sy-mandt.
  lw_legs-lifnr = 'V00003'.
  lw_legs-truck_no = 'TRK003'.
  lw_legs-trip_no = 'TRP0000000003'.
  lw_legs-counter = '01'.
  lw_legs-shnumber = 'SH003'.
  lw_legs-distance = '0100'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Leg 2: Also Loaded
  lw_legs-counter = '02'.
  lw_legs-shnumber = 'SH004'.
  lw_legs-distance = '0120'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Call function module
  CALL FUNCTION 'ZSCE_CTD_ERUNDIS_RULE'
    EXPORTING
      iv_simulation_mode = 'X'
    IMPORTING
      ev_status          = gv_status
      ev_message         = gv_message
      ev_trips_processed = gv_trips_processed
      ev_trips_qualified = gv_trips_qualified
    TABLES
      it_trip_header     = gt_trip_header_in
      it_trip_legs       = gt_trip_legs_in
    CHANGING
      ct_trip_header     = gt_trip_header_out
      ct_trip_legs       = gt_trip_legs_out
    EXCEPTIONS
      configuration_error = 1
      data_inconsistency  = 2
      technical_error     = 3
      OTHERS              = 4.

  IF sy-subrc <> 0.
    WRITE: / 'Test Case 03 FAILED: Exception raised', sy-subrc.
  ELSE.
    WRITE: / 'Results:'.
    WRITE: / '  Status:', gv_status.
    WRITE: / '  Message:', gv_message.
    WRITE: / '  Trips Processed:', gv_trips_processed.
    WRITE: / '  Trips Qualified:', gv_trips_qualified.

    " Verify results - should not qualify (no empty legs)
    IF gv_status = '01' AND gv_trips_qualified = 0.
      WRITE: / 'Test Case 03 PASSED', icon_led_green AS ICON.
    ELSE.
      WRITE: / 'Test Case 03 FAILED', icon_led_red AS ICON.
    ENDIF.
  ENDIF.

  SKIP 2.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  TEST_CASE_04
*&---------------------------------------------------------------------*
*       Test Case 04: Multiple Empty Legs, one exceeds threshold
*----------------------------------------------------------------------*
FORM test_case_04.

  DATA: lw_header TYPE gty_trip_header,
        lw_legs   TYPE gty_trip_legs.

  WRITE: / 'Test Case 04: Multiple Empty Legs'.
  WRITE: / '========================================'.

  " Prepare test data
  CLEAR: gt_trip_header_in, gt_trip_legs_in.

  " Trip Header
  lw_header-mandt = sy-mandt.
  lw_header-lifnr = 'V00004'.
  lw_header-truck_no = 'TRK004'.
  lw_header-trip_no = 'TRP0000000004'.
  lw_header-trip_status = '01'.
  lw_header-created_date = sy-datum.
  APPEND lw_header TO gt_trip_header_in.

  " Leg 1: Loaded
  lw_legs-mandt = sy-mandt.
  lw_legs-lifnr = 'V00004'.
  lw_legs-truck_no = 'TRK004'.
  lw_legs-trip_no = 'TRP0000000004'.
  lw_legs-counter = '01'.
  lw_legs-shnumber = 'SH005'.
  lw_legs-distance = '0100'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Leg 2: Empty (below threshold)
  lw_legs-counter = '02'.
  lw_legs-shnumber = ''.
  lw_legs-distance = '0030'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Leg 3: Empty (exceeds threshold)
  lw_legs-counter = '03'.
  lw_legs-shnumber = ''.
  lw_legs-distance = '0080'.
  APPEND lw_legs TO gt_trip_legs_in.

  " Call function module
  CALL FUNCTION 'ZSCE_CTD_ERUNDIS_RULE'
    EXPORTING
      iv_simulation_mode = 'X'
    IMPORTING
      ev_status          = gv_status
      ev_message         = gv_message
      ev_trips_processed = gv_trips_processed
      ev_trips_qualified = gv_trips_qualified
    TABLES
      it_trip_header     = gt_trip_header_in
      it_trip_legs       = gt_trip_legs_in
    CHANGING
      ct_trip_header     = gt_trip_header_out
      ct_trip_legs       = gt_trip_legs_out
    EXCEPTIONS
      configuration_error = 1
      data_inconsistency  = 2
      technical_error     = 3
      OTHERS              = 4.

  IF sy-subrc <> 0.
    WRITE: / 'Test Case 04 FAILED: Exception raised', sy-subrc.
  ELSE.
    WRITE: / 'Results:'.
    WRITE: / '  Status:', gv_status.
    WRITE: / '  Message:', gv_message.
    WRITE: / '  Trips Processed:', gv_trips_processed.
    WRITE: / '  Trips Qualified:', gv_trips_qualified.

    " Verify results - should qualify (one empty leg exceeds)
    IF gv_status = '00' AND gv_trips_qualified = 1.
      WRITE: / 'Test Case 04 PASSED', icon_led_green AS ICON.
    ELSE.
      WRITE: / 'Test Case 04 FAILED', icon_led_red AS ICON.
    ENDIF.
  ENDIF.

  SKIP 2.

ENDFORM.

" END: Cursor Generated Code
